### ISSUE TITLE
Add a "Remove All Active Abilities By Class" method on the ASC

### ISSUE THREAD

**Issue by LeoFabre** [reznok/GMCAbilitySystem#16]
Title says it all !
Can be useful to have if you activate several abilities that are children of the given class for example.

I might implement this myself later, leaving this as a TODO :)

**Comment by reznok** [comment]
Similar to GAS, I was planning on adding a way to remove abilities by tag. I believe GAS has a property for Effects that's "Cancel Abilities With Tag".

**Comment by Packetdancer** [comment]
This should actually be closed out, as `RemoveEffectByTag` has been in place for a while now!

**Comment by Packetdancer** [comment]
Wait, I misread this, it's ability and not effect. :|

**Comment by Aherys** [comment]
Implemented in https://github.com/Aherys/DeepWorlds_GMCAbilitySystem/commit/d814d9ca139bac64ef2d411c48f129ece4b5d988

**Comment by Aherys** [comment]
Is now PR #64

**Comment by LeoFabre** [comment]
> Is now PR #64 

Very cool, thanks !

**Comment by LeoFabre** [comment]
Looking at the code, it looks like it's by *tag* and not by *class*, but actually having it by tag is more powerful.

**Comment by Aherys** [comment]
There is both.

```cpp
	UFUNCTION(BlueprintCallable, DisplayName="End Abilities (By Tag)", Category="GMAS|Abilities")
	// End all abilities with the corresponding tag, returns the number of abilities ended
	int EndAbilitiesByTag(FGameplayTag AbilityTag);

	UFUNCTION(BlueprintCallable, DisplayName="End Abilities (By Class)", Category="GMAS|Abilities")
	// End all abilities with the corresponding tag, returns the number of abilities ended
	int EndAbilitiesByClass(TSubclassOf<UGMCAbility> AbilityClass);```
