### ISSUE TITLE
Demo Crashes when Using Listen Server and 2 Players

### ISSUE THREAD

**Issue by Nasuru** [reznok/GMCAbilitySystem#20]
Hi, was trying it out with the demo in the discord and it works fine and nice with a single player, but when 2 players with listen server it crashes when loading up. I put it into debug and the exception is in SyncCore.h on Line 195 where Index is -1 causing the exception. I didn't change anything after downloading the demo. I attached logs to help.

[GMCAbilitySystem_Demo.log](https://github.com/reznok/GMCAbilitySystem/files/14545827/GMCAbilitySystem_Demo.log)

**Comment by reznok** [comment]
Did you modify the `GMCCore.build.cs` and add the `StructUtils` and `GMCAbilitySystemTypesInclude` modules?

**Comment by Nasuru** [comment]
I was not reading carefully haha, that worked. Thanks!
