### ISSUE TITLE
Add an AnimInstance subclass with Gameplay Tag Bindings

### ISSUE THREAD

**Issue by LeoFabre** [reznok/GMCAbilitySystem#22]
Lyra has a custom anim instance class that has a [Gameplay Tag Binding map (docs)](https://docs.unrealengine.com/5.3/en-US/animation-in-lyra-sample-game-in-unreal-engine/#gameplaytagbindings) [(Lyra Anim Instance source)](https://github.com/EpicGames/UnrealEngine/blob/release/Samples/Games/Lyra/Source/LyraGame/Animation/LyraAnimInstance.h), which enables the ABP to thread-safely update bool fields to match the presence/absence of mapped GameplayTags on the owning pawn's ASC.

Again, I will need this in my game, and I'll contribute this when I'm done making it (no ETA at all)

Cheers !

**Comment by Packetdancer** [comment]
I already did something akin to this -- but more focused -- in my own project.

That said, I think the better way to do this would be to literally just create an equivalent to GAS's tag bindings, as having a way to have properties set automatically (and in a thread-safe way) based on tags could potentially be useful even outside of animation blueprints.

(Plus, it's about the same amount of work either way, and one way is useful globally as opposed to just in animation blueprints.)

**Comment by LeoFabre** [comment]
Totally agree !

**Comment by Packetdancer** [comment]
There's now a pull request against the dev branch which contains the requested feature. :)
