### ISSUE TITLE
Refactor StartingAbilityMap to an Array instead of a single variable

### ISSUE THREAD

**Issue by LeoFabre** [reznok/GMCAbilitySystem#23]
This would be useful to have to enhance modularity.

For example, a project could have a DefaultAbilityMap and a ShootingAbilityMap, and users could choose to have only the first or have both added to their character, depending on the need to be able to shoot or just roam around unarmed.

We can also make the AbilityMap DataAsset to also hold tags to add to the ASC's StartingAbilities GameplayTagContainer when the AbilityMap is granted to the ASC, also in the spirit of modularity.

What do you think about that ?

Cheers !

**Comment by reznok** [comment]
I think it can be an Array, we already do that with Attributes, so it would function similarly. 

A bool for "Add To Starting Abilities" (or similar) would make sense too. 

👍

**Comment by LeoFabre** [comment]
Yeah that bool is a good idea.
