### ISSUE TITLE
Port GAS's WaitGameplayTag AbilityTask to GMAS

### ISSUE THREAD

**Issue by LeoFabre** [reznok/GMCAbilitySystem#24]
This will be useful in my game, I might implement this at some point, feel free to do it if you need it before I do ;)

[GAS WaitGameplayTag source](https://github.com/EpicGames/UnrealEngine/blob/release/Engine/Plugins/Runtime/GameplayAbilities/Source/GameplayAbilities/Private/Abilities/Tasks/AbilityTask_WaitGameplayTag.cpp)

Cheers !

**Comment by petegilb** [comment]
This already exists! I added it for the demo. It’s called SetTargetDataGameplayTag or something like that
