### ISSUE TITLE
Attribute Clamping

### ISSUE THREAD

**Issue by reznok** [reznok/GMCAbilitySystem#46]
It's currently possible to clamp attributes by hooking into the OnChange events, but it should be possible to add Clamping directly into the attribute data assets.

Needs to support clamping an attribute via another attribute. Example: Clamping a "Health" attribute between 0 and "MaxHealth" attribute value.

**Comment by Packetdancer** [comment]
This should probably be closed since gil made this change like... 3 weeks ago. :)
