### ISSUE TITLE
Add an ASC Getter to the GMAS_Pawn class

### ISSUE THREAD

**Issue by LeoFabre** [reznok/GMCAbilitySystem#57]
Already have this in my project, will most probably contribute it today after work.
I have merged some features from Lyra in my project and needed that getter, figured out that some people might also need it later :)

**Comment by Aherys** [comment]
Hum, correct me if i'm wrong, but isn't GMASPawn only here for demonstration, and GMC Pawn considered as the default base ?

**Comment by Packetdancer** [comment]
GMAS Pawn already has this; the component is also a property, as `AbilitySystemComponent`, and can be just dragged into Blueprints (or accessed as a field on the class in C++). Unless I'm misunderstanding you here?

Though, Aherys is also correct inasmuch as GMAS Pawn is merely a convenience class; it's not a required pawn, it's merely a pawn that does a bunch of the setup for you already.

**Comment by LeoFabre** [comment]
Ah that's true ! 
Nevermind then, I must have been tired when I made it :')
