### ISSUE TITLE
Move Ability early check before instanciation

### ISSUE THREAD

**Issue by Aherys** [reznok/GMCAbilitySystem#62]
Currently, an ability is instancied, then check are done, and the ability immediatly end before it.

Some check, like Tag Check, would benefit to be moved before the instanciation to avoid the cost of it.
It would be also usefull to provide a static function (overridable in c++) to have custom pre-check for an ability in the same spirit (Like sanity of required variables).

**Comment by petegilb** [comment]
https://github.com/reznok/GMCAbilitySystem/pull/60 think Pax already did this too

**Comment by Aherys** [comment]
After check, change not present in #60.

Will be added in a PR in --dev

**Comment by Aherys** [comment]
Implemented in https://github.com/Aherys/DeepWorlds_GMCAbilitySystem/commit/c580300e7f5d6be4eeb6db09396db5c0bf161db7

**Comment by Aherys** [comment]
Is now PR #64
