### ISSUE TITLE
WaitForInputKeyRelease not working

### ISSUE THREAD

**Issue by rafadsm** [reznok/GMCAbilitySystem#69]
\\Title
You can get state of the input action only the first frame when the input changed, the value is always false, so it will be trigger every frame
I don't know if it worked before, but currently, it is not possible to get the input value in any other frame other than a frame in which the input was triggered

To test, you can set tick to show the input value
you will see it will be false even when you are holding it
the value will only be true if it is for the same trigger frame

so `WaitForInputKeyRelease` will always be triggered, even if the input is pressed(hold) as its value will be false in all frames

**Comment by Aherys** [comment]
Hello, in the master branch or in the dev branch ?

Cause there is no new commit in the master since one month, so there is no change in the behavior.
However, in the master, or in the dev, WaitForInputKeyRelease is working fine on my side. Are you sure you are using the GMAS one, and not the GAS one ?

**Comment by rafadsm** [comment]
Im using dev branch, unreal engine version 5.4.1, and its not GAS

Below is the video showing the problem in practice
In the video i hold the button, but ability always call "completed" on the event
Also, im checking input value pressing Z when the input is pressed(hold)
The value should be true instead always false
Well, the engine probably made some change to the boolean value input that caused WaitForInputKeyRelease to break

[https://streamable.com/yhch4f](https://streamable.com/yhch4f)

**Comment by Aherys** [comment]
We made change to the dev branch today, and this is mine change so it's maybe a bug in result of this.
That is true it's not tester on 5.4.1 but on 5.3.2 rn.

I will investigate tomorrow.

**Comment by Aherys** [comment]
Hello must be resolved by https://github.com/reznok/GMCAbilitySystem/pull/70

We basically change the way ability task are binded cause we identified a probable memory corruption, so it must cover every case now, including 5.4.

**Comment by rafadsm** [comment]
Oh thank you very much for the correction :heart:
I tested your changes and now it seems to be working correctly.

**Comment by Aherys** [comment]
You can thanks @Erlite, his is the one who worked on that =]

**Comment by petegilb** [comment]
fixed in #70
