### ISSUE TITLE
WaitDelay node always cancels ability when run on dedicated server

### ISSUE THREAD

**Issue by solomon-gumball** [reznok/GMCAbilitySystem#88]
From discord post:

When I activate an ability for an NPC on a dedicated server (Net mode -> Play as client) the wait delay node I have in that ability seems to cancel the ability shortly after activation (before the 5s timer completion).  

![image2](https://github.com/reznok/GMCAbilitySystem/assets/5566649/ee72c177-6e23-4fa0-ab3a-5eda12c01c4d)

It seems it's due to this heartbeat timeout check.  This is the line that is ending the ability early:
![image](https://github.com/reznok/GMCAbilitySystem/assets/5566649/220f9982-6a82-40cd-8bb9-251d94f1c338)

This does not happen at all when I play as server.

**Comment by reznok** [comment]
Fixed at some point
