### ISSUE TITLE
[dev] Nested Gameplay Tags Add/Remove Bug

### ISSUE THREAD

**Issue by reznok** [reznok/GMCAbilitySystem#98]
![image](https://github.com/user-attachments/assets/33b9f429-d23a-46af-b55b-2cc43212d505)
Bringing this over from [discord](https://discord.com/channels/914284312701059103/1294328945159700480) to ensure vis and in case someone has the chance to look into it. 

Replicable in fresh project. An issue occurs when nested gameplay tags are granted and removed with effects.
The effects are removed, but the granted tag is not removed correctly.
In the screenshot scenario, State.Test granted tag is never removed. 
Having the effects added or removed in different order does not change the outcome.

_Originally posted by @Crezetique in https://github.com/reznok/GMCAbilitySystem/issues/95#issuecomment-2472427991_

**Comment by Crezetique** [comment]
_~~Note: Fixed in DeepWorld fork, can be closed once merged into main/dev.~~_

See next comment.

**Comment by Crezetique** [comment]
Issue is updated in DeepWorld's PR.

The issue continues to occur only when "Preserve Granted Tags If Multiple" is true.
![image](https://github.com/user-attachments/assets/7e6a0c1a-1e24-41d2-b34c-2902610665f5)

**Comment by Crezetique** [comment]
Issue has been updated in DeepWorlds' PR #100 .

The issue continues to occur only when "Preserve Granted Tags If Multiple" is true.
![image](https://github.com/user-attachments/assets/7e6a0c1a-1e24-41d2-b34c-2902610665f5)

**Comment by Aherys** [comment]
I take the solving of the issue.

**Comment by Aherys** [comment]
Attempt to fix the issue in commit 3dec47a in DW Fork.
https://github.com/DeepWorldsSA/DeepWorlds_GMCAbilitySystem/commit/3dec47a3878788f6e9444583ef857c1b3296013c

In wait of @Crezetique to confirm the fix is valid.

**Comment by Aherys** [comment]
Issue has been confirmed fixed by @Crezetique.

Closing ticket, commit https://github.com/reznok/GMCAbilitySystem/commit/3dec47a3878788f6e9444583ef857c1b3296013c will be merge into reznok:dev.
